### ISSUE TITLE
"Invalid collection" Icestudio 0.5.0 and 0.5.1 Nightly

### ISSUE THREAD

**Issue by jcarolinares** [Obijuan/VGA_basics#1] opened 2020-09-19 16:21 UTC
Hello!!!

I've tried to download the development collection and Icestudio said me that the collection is invalid, I wasn't able to catch any log message from the command lines or chrome version. 

Any idea what could be the reason?

The setup is:

* Ubuntu 16.04
* Icestudio 0.5.0 and 0.5.1

Regards :) !

**Comment by Obijuan** [comment] 2020-09-19 17:43
Hi!

I cannot reproduce your problem. I have download the repo (as .zip) and install it (Tools/Collections/Add) from icestudio nightly 0.5.1n200523. The collection is correctly loaded and it is shown under the Select/Collection menu

This is the .zip I've downloaded: 

[VGA_basics-master.zip](https://github.com/Obijuan/VGA_basics/files/5250293/VGA_basics-master.zip)


![VGA-basics-01](https://user-images.githubusercontent.com/1286062/93685509-36df1880-fab0-11ea-8d7b-5bbd94bc7641.png)

**Comment by Obijuan** [comment] 2020-09-30 07:53
Hi @jcarolinares !  is it working for you? Please, try to add the previous .zip as a collection and check if it is shown in icestudio. If not, it would be great that you write down the steps you are doing so that we can reproduce the bug. Thanks a lot :-)

**Comment by Obijuan** [comment] 2020-11-11 07:06
As i do not have feedback, i assume that everything is working ok. I close this issue

**Closed as completed by Obijuan** 2020-11-11 07:06 UTC

**Comment by jcarolinares** [comment] 2020-11-11 19:27
I'm so sorry Juan for my total lack of following the problem, I've totally forgot this. I don't have Ubuntu 16.04 anymore but I've tested with the nightly 0.5.1n200523 and Ubuntu 20.04 and everything seems that is working fine. So I assume it won't be a problem in the near future for anybody.

thank you so much for your follow up, take care!

**Comment by Obijuan** [comment] 2020-11-17 08:23
No problem! Happy to know that everything works ok! Thanks for the update! :-)
